### ISSUE TITLE
[Discussion] Shape of data-source

### ISSUE THREAD

**Issue by ecwyne** [gramps-graphql/gramps-express#39]
@jlengstorf I really enjoyed your talk today at GraphQL Summit and having the opportunity to speak with you afterwards. Thank you!

(sorry, this ended up being longer than I expected)

I've taken some time to grok the gist of how data-sources are created and how gramps-express consumes them. As I understand it a data source provides four values.

### Existing
1. context: `String` (used to set property name on each queries `context`)
2. model: `Model` (added to each queries `context`)
3. schema: `String` (text of the Schema)
4. resolvers `Object` (object with `queryResolvers`, `mutationResolvers`, `dataResolvers`, `mockResolvers`, and *someday* `subscriptionResolvers`)

This took some time to wrap my mind around. I think this is because these values are different than what `makeExecutableSchema` and `addMockFunctionsToSchema` expect.

### Proposed
I believe that the essence of a data source is more clearly captured with the following four values (which can be passed almost directly into `makeExecutableSchema` and `addMockFunctionsToSchema` (and query context).

1. typeDefs: `String` (text of the [Schema](http://dev.apollodata.com/tools/graphql-tools/generate-schema.html#example))
2. resolvers: `Object` (the exact object that would be passed to [`makeExecutableSchema`](http://dev.apollodata.com/tools/graphql-tools/generate-schema.html#makeExecutableSchema) in a standard apollo-server, including `Query`, `Mutation`, and `Subscription`)
3. mocks: `Object` (the exact object that would be passed to [`addMockFunctionsToSchema`](http://dev.apollodata.com/tools/graphql-tools/mocking.html#addMockFunctionsToSchema))
4. context: `Function` (same as function passed directly into [graphqlExpress](http://dev.apollodata.com/tools/apollo-server/setup.html#options-function)

I believe the `Model` + `Connector` pattern you've created is *one* way to wire up the `context` and `resolvers`. Every graphql developer should be familiar with creating `typeDefs`, `resolvers`, and `mocks` (they do it every day!)

### Specifics (implementation details)
A new [combineResolvers](http://dev.apollodata.com/tools/graphql-tools/generate-schema.html#makeExecutableSchema) would look something like this:
```javascript
import merge from 'lodash.merge';
// simply deep merge the objects
export const combineResolvers = (sources, initial = {}) => sources.reduce(merge, initial)
```

a new [getSchema](https://github.com/gramps-graphql/gramps-express/blob/master/src/lib/configureSchema.js#L40) would look like this:
```javascript
export const getSchema = ({ sources, logger, options }) =>
  makeExecutableSchema({
    // Combine all the schema definitions into an array.
    typeDefs: [rootSchema, ...sources.map(source => source.typeDefs)],
    resolvers: combineResolvers(sources.map(source => source.resolvers), {
        Query: {grampsVersion: () => pkg.version},
        Mutation: {grampsPing: () => 'GET OFF MY LAWN'}
      }
    },
    logger,
    ...options,
  });

export const addMockFunctions = ({ sources, schema, options }) => {
  addMockFunctionsToSchema({
    mocks: combineResolvers(sources.map(source => source.mocks)),
    schema,
    ...options,
  });
```

Finally, `context` is added like so: [here](https://github.com/gramps-graphql/gramps-express/blob/master/src/gramps.js#L82)

```javascript
return (req, res, next) => {
    const context = sources
      .map(source => source.context)
      .reduce((combined, fn) => merge(combined, fn ? fn(req) : {}), {});

    req.gramps = {
      schema,
      context,
      formatError: formatError(logger),
      ...apolloOptions.graphqlExpress,
    };

    next();
  };
```

**Comment by ecwyne** [comment]
As an aside, an existing GrAMPS package could be mapped to the proposed shape like so.

```javascript
const convert = ({context, model, schema, resolvers}) => ({
  typeDefs: schema,
  resolvers: {
    Query: resolvers.queryResolvers,
    Mutation: resolvers.mutationResolvers,
    Subscription: resolvers.subscriptionResolvers,
    ...resolvers.dataResolvers
  },
  mocks: resolvers.mockResolvers,
  context: () => ({[context]: model})
});
```

**Comment by jlengstorf** [comment]
Hey, @ecwyne — thanks for putting this together. You've brought up some good points.

We talked about a lot of this at the GraphQL Summit, but to recap our discussion and try to hash out some of these thoughts more concretely, let me run through 1) the primary goal of GrAMPS as I see it, and 2) the motivation behind how I initially structured the arguments.

## 1. The Primary Goal of GrAMPS

Beyond the obvious intention of GrAMPS (allowing discrete data sources to be composed together into a single GraphQL endpoint), the primary intention of GrAMPS is to try and unify some structure around creating data sources on the server side. My mental model for this is functional composition, so I picture a GrAMPS-powered server being able to do things like this (in pseudo-code):

```js
app.use(grampsAddRedisCache(redisInstance));
app.use(grampsAddHealthCheck());
app.use(grampsExpress(...));
```

Or, if we move away from middleware as @jkrems is proposing in #41, it could turn into an actually functional approach:

```js
const getGramps = compose(
  addRedis(redis),
  addHealthCheck,
  combineDataSources
);

const gramps = getGramps({ dataSources: [dsOne, dsTwo] });
```

To do this, data sources need to be predictable in their public APIs. This was the motivation for exporting an object from each data source.

However, the current implementation has a few things baked in that I think need to be reconsidered if that pattern is going to be truly flexible:

First, the `GraphQLConnector` class currently makes a lot of assumptions based on wrapping REST APIs. If we also want to support GraphQL Native data sources, this would require a different set of assumptions.

As designed, the default would be to add a base class/interface for the `GraphQLConnector`, then extend that with `GraphQLRESTConnector` or `GraphQLDBConnector`, then extend _that_ with the actual data source, but then we're looking at multiple inheritance, and that'll end up being a big gross mess as things progress. (Created #42 to track this specifically.)

I also have some boilerplate in place for using Redis, because that's what IBM does, but additional middleware is required (which currently doesn't exist in public because I haven't had the chance to move it yet) to actually add a Redis instance to the connector. This is a terrible approach that I want to get away from — I've opened #43 to track this.

I wonder if there's a way to approach this that removes the need for classes altogether, but I don't have a fully formed idea for how this could work at the moment.

## 2. Initial Structure

As I was onboarding team members with little or no GraphQL experience — especially those who were earlier in their careers, I was paying attention to the vocabulary and abstractions that seemed to click as they explored these new ideas.

Whenever we talk about something like this:

```graphql
type User {
  name: String!
}
```

We refer to it as a "schema" — so while I'm not necessarily opposed to calling it `typeDefs`, I feel like it's an extra layer of jargon that maybe isn't required. (With the trade-off being that we're asking experienced GraphQL devs to unlearn `typeDefs`.)

---

Another area where new developer struggled was with the concept of resolvers. Drawing a clear delineation in terminology between the resolvers that fetch data objects (`queryResolvers`) and the resolvers that map JSON to the schema (`dataResolvers`) helped clarify the mental model. I'm hesitant to move them back into a single object, but definitely willing to discuss it further. 

It does raise a good point, though: what happens when a query has a field that requires another data access call to be made?

For example:

```graphql
query {
  getAuthor(id: 123) {
    name

    # Kicks off an additional request for posts
    posts {
      title
    }
  }
}
```

Where does that `posts` field resolver live? It's a field, so it seems like it should be a `dataResolver`, but it also requests data, so it's kind of a `queryResolver` — that's potentially confusing. But if we eliminate the delineation, what can we do to address the lack of clarity when onboarding new developers? I don't have any answers; I'm basically just stream-of-consciousness working through things here. 😅

---

I do think it would be a good idea to extract the mocks into their own field, and potentially their own file. Originally I had thought that mock _resolvers_ should live with all resolvers, but they're a special case with special logic, so that definitely makes sense to isolate them and make that more explicit.

So maybe the new export looks something like this:

```
context: String
model: Object
schema: String
resolvers: Object
mocks: Object
```

I think there's a good amount of thinking and experimentation to be done around what the `model` actually returns, and how we can make it flexible without sacrificing the ability to add features against a predictable API.

Let's move discussion on the relevant model topics to their respective issues for the sake of keeping things somewhat-threaded. Otherwise, I'd love to hear your thoughts on this.

**Comment by ecwyne** [comment]
@jlengstorf I do now understand more of the motivation for specifying/prescribing a particular structure of model/connector to allow for additional instrumentation. I agree that defining the objective of GrAMPS is important as it will inform every decision surrounding the project.

As I've considered patterns to add instrumentation round data-sources I began to ask myself more basic questions. **"Is the construct of a `data-source` the correct level at which to add instrumentation?"** **"What does it even mean to add caching to a `data-source`"** It seems to me that instrumentation like caching belongs either around the entire query (ie. potentially across multiple data-sources) or on a per-resolver basis (which then really should be done by the data-source author themselves. [Sashko's talk at GraphQL Summit](https://about.sourcegraph.com/graphql/the-graphql-stack-how-everything-fits-together/) very much informed where I was thinking caching **should** fit in a graphql server (ie. allowing type defs and queries include a "@maxAge" directive).

I started to see that a real strength and value-add for GrAMPS may be to take a bunch of data-sources and create both a graphql server from them *AND* a [GraphQL Gateway](https://d33wubrfki0l68.cloudfront.net/aa1efcee85e706b864d39e909017e27ce2b96b82/ad330/blog-images/a-new-component-in-graphql-stack.jpg) (like Apollo-Engine or potentially use Apollo-Engine directly) automatically. This gateway can add the caching, logging, etc. defined by the data-sources using strategies like [apollo-tracing](https://github.com/apollographql/apollo-tracing). This way data-source authors don't need to model their data-source in any prescribed way and users of GrAMPS would get all of the added benefits of automatically combining data-sources and all of the benefits possible with a gateway.

I realize that this is an entirely different take on what GrAMPS *is* and would constitute a ton of work but I think it hits that sweet spot of allowing for flexibility for data-source authors while also providing a way to add lots of additional features out of the box to users. I also see the potential for an architecture like this to lead to a "Storybook for GraphQL" where GrAMPS could provide an awesome experience for data-source authors to easily interact with their data as they're designing their data-sources.

**Comment by jlengstorf** [comment]
I’ll need to respond to this in more detail, but quickly: the caching I’m talking about is on the API side. So the data source is able to specify a caching strategy for the REST data, which has allowed us to wrap endpoints that are potentially slow or unstable and increase their reliability. I think this would be complementary to the Apollo Engine approach, which is caching the GraphQL query results as you described.

**Comment by ecwyne** [comment]
I look forward to your more detailed thoughts!

I am curious if you have thoughts on a generalizable approach to caching the API side. That is to say how it would look for non-REST data-sources (which is my situation, so I feel compelled to champion a solution that would work for more than just wrapping REST endpoints)

Another example where caching doesn't really make sense either would be static data. I could easily see using a data source that provides an Enum of US States (or their coordinates, etc.) that doesn't touch the network at all. Would the author of that data-source be expected to provide a way to have its results cached in redis?

I think the data-sources themselves may provide context-aware caching, but I'm not convinced that GrAMPS (the core framework) needs to concern itself with providing that. I can easily see GrAMPS (the org) providing a repeatable way of doing so for REST-wrapping data-sources

**Comment by jlengstorf** [comment]
Hey, @ecwyne — I did some additional thinking on this, and I think we're able to reconcile both ideas (predictable models + flexibility).

If we look at what we'll need for REST in the connector layer (which is where caching would happen), everything is built around REST. Which makes sense. But _everything_ in there breaks down when we use it for another purpose, such as direct DB access.

To try and wrap my head around this, I created the simplest possible data source I could come up with, and did it all in one place:

```js
const DataSource = {
  context: 'Generic',
  schema: 'extend type Query { example: MY_Example! } type MY_Example { whoami: String! }',
  model: {
    getExample: () => ({ whoami: pkg.name }),
  },
  resolvers: {
    queryResolvers: {
      example: (_, __, context) => context.Generic.getExample(),
    },
    mockResolvers: {
      MY_Example: () => ({
        whoami: () => 'I don’t know',
      }),
    },
  },
};
```

A model is just a generic object with methods to access data. (Duh, but I needed to look at it from a different angle to see it.)

Where the power of the REST approach comes in (caching, etc.) is actually in the connector, which is entirely optional in reality. The benefits we offer for REST don't cross over to direct DB access or flat files, as you pointed out — but maybe that doesn't matter.

Looking at this, I'm wondering if it actually makes more sense to pull the model/connector stuff into helpers. So instead of having a `GraphQLConnector` class, we could spin out `@gramps/connector-rest` and `@gramps/connector-firebase`, `@gramps/connector-mongodb`, etc.

If these were set up in a way that additional middleware could quickly identify the connectors where it's useful and bypass those where it's not, then we kind of get to have our cake and eat it, too. For example:

- in the REST helpers, we attach the dataloader, optionally add Redis, etc.
- in a DB helper, we could add additional helpers as repeatable steps become apparent
- maybe flat file connectors just are what they are, and don't need any helpers

Using the class-based model, this could be as straightforward as changing from `GraphQLConnector` -> `GrampsConnectorREST` and checking for that in a helper, or using plain objects and setting a `connectorType` prop.

That way we're able to keep the benefits for REST-based data sources, but don't add unnecessary complications for other types.

What do you think?

**Comment by ecwyne** [comment]
I think that having different `@gramps/connector-rest`, `@gramps/connect-firebase`, `@gramps/connector-mongodb` packages is more ergonomic and usable.

Thinking through this also makes one thing fairly clear to me. **The main GrAMPS process can only communicate to connectors via environment variables** Connectors are hidden within the models (which are created by data-source authors) and therefore aren't visible to the main GrAMPS process in any other way.

Therefore connectors can be used in any way imaginable (because they get their context from `process.env`). Connectors could even be used directly from resolvers, they don't *need* to be within a model.

Additionally, I believe a data-source should be able to have multiple "models". For example, a twitter data-source could easily have a `TwitterUser` model and `TwitterTweet` model each with a `getById` and  `getByIds` methods. Instead of requiring data-sources to have **EXACTLY** one model, I believe the `context` function I originally described would allow for any number of models (or really anything at all) to be added to context of each query.

**Comment by jlengstorf** [comment]
Can you pseudo code that up a bit? I think I know where you're headed, but I'm a little wary of using env vars as the _only_ way to configure a connector. For example, how would someone instantiate and attach a Redis instance to all REST connectors?

**Comment by ecwyne** [comment]
I'd be happy to pseudo code this.

```javascript
import redis from 'redis';

const {GRAMPS_REDIS_URI} = process.env;

export class GrampsConnectorREST {
  redis = GRAMPS_REDIS_URI ? redis.createClient(GRAMPS_REDIS_URI) : false;
  cacheExpiry = 300;
  enableCache = true;
}
```

What other ways do you see that `@gramps/core` **could** communicate with connectors at __runtime__? Currently, do data-source authors have to pass in a redis instance themselves to their [connector](https://github.com/gramps-graphql/gramps-express/blob/master/src/helpers/GraphQLConnector.js#L39)?

**Comment by corycook** [comment]
I feel like `queryResolvers`, `mutationResolvers`, and `dataResolvers` adds a level of abstraction that makes GrAMPS more confusing than Apollo resolvers.

Given this schema
```graphql
extend type Query {
  users: [User]
}

type User {
  name: String
}
```

Here is a possible resolvers implementation in Apollo
```javascript
const resolvers = {
  Query: {
    users: (_, args, context) => context.model.getUsers(),
  },
  User: {
    name: user => user.name,
  },
};
```

And an equivalent implementation in GrAMPS:
```javascript
const resolvers = {
  queryResolvers: {
    users: (_, args, context) => context.PFX.model.getUsers(),
  },
  dataResolvers: {
    User: {
      name: user => user.name
    },
  },
};
```

The Apollo resolvers map directly to the schema and it is easy to see the correlation between the two. The connection between GrAMPS resolvers and the schema isn't as clear.

**Comment by jlengstorf** [comment]
Alright, I see my efforts to make a clearer distinction between resolvers that _get_ data vs. resolvers that _map_ data isn't doing what I'd hoped. So let's drop it and follow the Apollo convention. 😄 

I'm thinking that we should extract the core out (per #41) and refactor the data source base, and the breaking changes will result in a 1.0.0 release.

A data source in the 1.0.0 release will look like this, if I'm understanding everyone correctly:

```js
{
  context: String,
  schema: String,
  model: req =>  // returns an object with methods, e.g. { getById: () => ({ id: 123 }) }
  resolvers: Object // matches the format of Apollo resolvers
  mocks: Object // matches the format of Apollo mock resolvers
};
```
With a simple example looking like this:

```js
const DataSource = {
  context: 'Generic',
  schema: 'extend type Query { example: MY_Example! } type MY_Example { whoami: String! }',
  model: () => ({
    getExample: () => ({ name: 'Francis', age: 42 }),
  }),
  resolvers: {
    Query: {
      example: (_, __, context) => context.Generic.getExample(),
    },
    MY_Example: {
      whoami: data => data.name,
    },
  },
  mocks: {
    MY_Example: () => ({
      whoami: () => 'I don’t know',
    }),
  },
};
```

Each top-level data source component except the `context` field will be split into its own file by default in the `@gramps/data-source-base` setup.

Probably we should include a transformer function that will accept the current data source format, log a deprecation error w/links to the new format, and return a 1.x formatted data source.

Which gives us the following steps:

- [ ] Create a `@gramps/core` repo
- [ ] Move the data source combination functionality into `@gramps/core`
- [ ] Refactor the reducers to use the 1.x data source format
- [ ] Write a 0.x data source transformer function (@ecwyne already did most of this work)
- [ ] Refactor `@gramps/data-source-base`
- [ ] Update the docs to use the new data source format
- [ ] Update the XKCD data source for use in the docs
- [ ] Update existing example implementations
- [ ] Update `@gramps/gramps-express` to import and use the `@gramps/core` functionality
- [ ] Update and finish the quickstart docs (#23)

Am I missing anything?

**Comment by ecwyne** [comment]
This is amazing!

Two things come to mind that I want to make sure aren't overlooked.

1. With more alignment with Apollo, should we take another look at "`schema`" vs "`typeDefs`"?
2. How can a data-source attach more than one `Model` to context?

**Comment by jlengstorf** [comment]
I'll open this up for voting. I prefer `schema`, because that's how people refer to it when speaking and writing about GraphQL schemas, but if everyone else feels that `typeDefs` is more appropriate, then I'll go with it.

There's nothing preventing a dev from attaching multiple models to a connector. As is, there's a loose convention of something like this:

```js
model: new Model({ connector: new Connector() })
```

This could be extended to:
```js
{
  model: new Model({
    userConnector: new UserConnector(),
    postConnector: new PostConnector(),
  })
}
```

Is that what you mean? If not, can you pseudo-code the API you're looking for?

**Comment by ecwyne** [comment]
```graphql
# typeDefs
type Query {
  userById(id: ID!): User
  postById(id: ID!): Post
}

type User {
  id: ID!
  name: String!
  posts: [Post]!
}

type Post {
  id: ID!
  authorId: ID!
  author: User!
  body: String!
}
```

```javascript
// Models
class User {
  constructor(obj){
    Object.assign(this, obj);
  }

  get posts(){
    return Post.getByUserId(this.id)
  }

  static getById(){
    ...
  }
}

class Post {
  constructor(obj){
    Object.assign(this, obj);
  }

  get author(){
    return User.getById(this.authorId)
  }

  static getById(){
    ...
  }

  static getByUserId(userId){
    ...
  }
}
```

```javascript
// Resolvers

export const resolvers = {
  Query: {
    userById: (_, {id}, context) => context.User.getById(id),
    postById: (_, {id}, context) => context.Post.getById(id)
  }
}
```

### Proposed API
A function that takes the request and returns an object to be merged with every other data-source's context (see original post)
```javascript
export const context = req => ({
  User,
  Post
})
```

This also allows for request-specific models. E.g. using `req.user` from [passport](http://www.passportjs.org/)

```javascript
export const context = req => ({
  me: new User(req.user),
  User,
  Post
});
```

**Comment by jlengstorf** [comment]
I worry that this can get messy in a hurry. What if two data sources use `User` in their model?

I think I'd prefer to keep these under a data source namespace:

```js
userById: (_, { id }, context => context.MyDataSource.Users.getById(id),
```

That helps keep the data source link clear — if the data source is called `BlogPosts` and you look up authors in `context.Author.getById()`, that's a little confusing. `context.BlogPosts.getAuthorById()` is my preference, but `context.BlogPosts.Author.getById()` also works.

Making the model (optionally) a callback works for me, though:

```js
{
  model: req => {
    MyDataSource: {
      me: new User(req.user),
      User,
      Post,
    },
  }.
}
```

Thoughts?

**Comment by ecwyne** [comment]
I agree that avoiding collisions (and alerting when there is a collision) is vital.

I do think `namespace` is clearer than `context`. I'd be happy if a data-source had the following shape:
```
namespace: String
model: Object|Function(req => Object)
typeDefs: String
resolvers: Object
mocks: Object
```

**Comment by jlengstorf** [comment]
`namespace` works for me, where the GrAMPS pattern would be to add `model`(s) to the `context` using:

`context.namespace.model`

**Comment by jlengstorf** [comment]
Updated https://github.com/gramps-graphql/gramps-express/issues/39#issuecomment-340498789 with the proposed API.

@corycook @ryanomackey @jkrems please check out the proposed structure and let us know if you see any edge cases or issues before I start pulling the core into a new repo.

**Comment by ecwyne** [comment]
http://dev.apollodata.com/tools/graphql-tools/schema-stitching.html#mergeSchemas

Looking ahead to stitching together two executable schemas...

`mergeSchemas` expects an array of executable schemas (which we create using `typeDefs`, and `resolvers`) **AND** stitching resolvers which has a shape of `(mergeInfo: MergeInfo) => IResolvers`

I would need to test to make sure both of these could work. But I see two options:

1. Have **separate** `resolvers` (Object) and `stitchResolvers` (Function) exported by each data-source
2. Have each data-source export **ONE** `resolvers` function that takes mergeInfo as its argument

This also may inform **how** GrAMPS combines data sources. It probably makes sense to take the following progression.

1. Map over each data-source and run `makeExecutableSchema` on **each**
2. Use `mergeSchemas` to combine schemas from Step 1 using any `stitchingResolvers` exported by data-sources
3. Create `context` for each request using `{[namespace]: model}`

**Comment by jkrems** [comment]
The API looks good! My only question would be: Should we encourage the use of `Symbol` for namespaces? Or npm package names? Just to make it harder for packages to collide by accident.

**Comment by ecwyne** [comment]
Another case for using `typeDefs`...

A data-source should be able to export **either**
1. `typeDefs` and `resolvers` in order to create an executable `schema`
2. The executable `schema` itself.

The second is particularly important for data-sources wrapping remote schemas. A remote schema doesn't have `typeDefs` and `resolvers` to be exported. But [makeRemoteExecutableSchema](http://dev.apollodata.com/tools/graphql-tools/remote-schemas.html#makeRemoteExecutableSchema) will gladly hand you a working executable `schema`

**Comment by corycook** [comment]
I agree with Eric that we should also be able to export an executable schema to cover advanced cases where the datasource wants to run autonomously and still be included in the schema provided by the GrAMPS server.

As a data source developer I'm wondering why I care about the namespace in the context.

```javascript
const resolvers = {
  items: (_, args, context) => context.MyNamespace.getItems(),
};
```

Really the rest of context is a mystery to me and under the control of other teams. So, what I really want to do is:

```javascript
const resolvers = {
  items: (_, args, model) => model.getItems(),
};
```

we could incorporate something similar to the hack I mentioned [here](https://humanhybrids.io/code/2017/10/28/migrating-to-gramps.html#context) to extract the proper context for each data source in GrAMPS.

**Comment by ecwyne** [comment]
I can't think of any reason that data-sources need access to the **full** context object, and the api is certainly more ergonomic if you don't have to call `context.namespace.method()` every time.

@jlengstorf let us know if/when there is any way we can help with moving to `@gramps/core`

**Comment by jlengstorf** [comment]
My concern with removing the namespace is that it makes this a little bit magic. Looking at @corycook's workaround, that's a pretty hairy set of helpers just to avoid using a namespace, and I'd argue that both the complexity of the workaround and the lack of a namespace result in less maintainable code.

If I create a data source called `MyData`, and I access the model methods through `context.MyData.methodName`, that intuitively makes sense. But if the `context` just changes between data sources, that's a little odd.

Another question about this is additional context applied organization-wide. For example, our GraphQL µ-service at IBM attaches `req` to the context for _all_ data sources. How does that work if we're abstracting the rest of the context away? I agree that most teams most likely _shouldn't_ have a reason to touch other contexts, but do we want to actually _enforce_ that? Is that going to come back and bite us later on?

This could also have a negative impact on debugging. If we drop it, we need to be paying attention to that.

I worry a little that removing a namespace in the context is a little bit of hacking around so it feels like it's not intended to be part of a greater combination of data sources. If I'm editing two data sources that have a `getById()` method, if they're not namespaced I may expect that they're the same thing. It's a small thing, but that cognitive overhead adds up during maintenance, especially if the person doing the maintenance isn't the person doing the maintaining.

My preference would be toward verbosity for the sake of clarity. I'm willing to give on this if no one else agrees with me, but let's make sure we the trade-offs are super clear.

**Comment by jlengstorf** [comment]
@ecwyne For schema stitching, I think we need to put some working examples together and see where this breaks down.

Currently, my gut feeling says that we'll do something like this, logically:

- Data Source A wants to add a subfield that accesses Data Source B
- Data Source A checks if Data Source B exists
- If so:
    - Data Source A extends its target type with the stitched field
    - Data Source A defines the resolvers to support the stitched field (another reason to keep the `context` namespaces)
- If not:
    - Stitching fails silently (OR, we could define the field and provide an error)

Data Source B would need to define its own schema stitching with Data Source A following the same logic above. In this way, each team is still able to control their own data source (a query to Data Source A that accesses data from Data Source B is still part of Data Source A, but Data Source B accessing Data Source A is not).

But again, I think we need to actually build a proof of concept and see if we can spot any challenges or useful patterns.

**Comment by jlengstorf** [comment]
Check out https://github.com/gramps-graphql/data-source-xkcd/pull/1 for an example of a working 1.0.0 data source.

**Comment by ecwyne** [comment]
@jlengstorf have you looked into the details of http://dev.apollodata.com/tools/graphql-tools/schema-stitching.html#mergeSchemas? It's actually pretty prescriptive about how to do schema stitching.

You provide an array of executable `schemas` and resolvers that provide a `fragment` and `resolve` fn for each field. That `resolve` function calls `mergeInfo.delegate()`. I have no doubt that this api is subject to change in the future, and GrAMPS may be able to provide some helpers to make things easier for data-source authors. But my sense is that staying as close to the Apollo api will serve GrAMPS well in the long run.

I'm happy to put together some working examples if we can get a `@gramps/core` up and running. I should be able to tinker with it enough to show how to set up schema stitching.

In pseudo-code

```javascript
const dataSources = [...];

const schemas = dataSources.map(({typeDefs, resolvers, schema}) => schema || makeExecutableSchema({typeDefs, resolvers}))

const stitchResolvers = dataSources.map(({stitchResolvers}) => ...combine them...)

const merged = mergeSchemas({
  schemas,
  resolvers: stitchResolvers
})
```

To answer you question to @corycook - to create a data-source for the [Universe GraphQL API](https://developers.universe.com/page/graphql-explorer) I would export the schema given to me using [makeRemoteExecutableSchema](http://dev.apollodata.com/tools/graphql-tools/remote-schemas.html#makeRemoteExecutableSchema) pointed to https://www.universe.com/graphql . **Remote schemas don't have `typeDefs` and `resolvers` to export, only the executable `schema`**

**Comment by corycook** [comment]
> My concern with removing the namespace is that it makes this a little bit magic.

To a data source developer or a new developer to GraphQL, how resolvers are called and how the context is wired to the resolver methods is all magic. `context.MyNamespace.get()` is the same magic as `model.get()`.

To experienced GraphQL developers they can treat the model just as they currently treat context.

This also helps with Apollo migrations where a single context is used. An Apollo implementation would be able to directly plug in their current context into the GrAMPS `model` and the resolvers would work.

Of course, we could also provide a separate tool to migrate an Apollo implementation to GrAMPS that could do this for them.

> if the context just changes between data sources, that's a little odd

A typical data source developer wouldn't see this difference or care. They would see that they have access to their own model in their resolvers. If they need access to a separate GrAMPS data provider they should be able to import the data source and use the model directly or use schema stitching.

My argument is that this removes the cognitive overhead by allowing the data source developer to focus on their concerns rather than worrying about what else might be in the context or what they can use in the context. If another team decides to take down their data source is that going to affect my code because I am depending on that context to be available? If I'm not controlling the GrAMPS instance then I really can't tell what context might contain.

I think that my ideal implementation of GrAMPS would support the following:

```javascript
const items = [];
module.exports = {
  name: 'MyDataSource',
  schema: `
    type Query {
      items: [Item]
    }
    type Item {
      id: ID
      text: String
    }
  `,
  resolvers: {
    Query: {
      items: (_, args, model) => model.getItems(),
    },
  },
  model: req => ({
    getItems: () => items,
  }),
};
```

and then a query

```graphql
query getItems {
  MyDataSource {
    items {
      id
      name
    }
  }
}
```

I think this would feel very natural to me. Everything that is available to me is a result of my implementation and I have a lot of control over how my code is executed.

If I'm being a jerk about this then I will shut up.

**Comment by ecwyne** [comment]
The more I think about it, the more I agree with @corycook 

When doing schema stitching Data Source A does not call Data Source B's resolvers directly, it uses `mergeInfo.delegate()` to delegate to Data Source B's resolvers

> This also helps with Apollo migrations where a single context is used. An Apollo implementation would be able to directly plug in their current context into the GrAMPS model and the resolvers would work.

This, I believe, is the strongest argument

**Comment by jlengstorf** [comment]
## First crack at the 1.x architecture:

I've extracted the core to https://github.com/gramps-graphql/gramps. @corycook @ecwyne @jkrems @ryanomackey if you want to fork it and submit PRs with anything I missed (and/or the changes we're still discussing here), that would be awesome.

## On removing the namespace and the maintainability of code

> My argument is that this removes the cognitive overhead by allowing the data source developer to focus on their concerns rather than worrying about what else might be in the context or what they can use in the context.

Let me make one more argument in favor of namespacing, and then I'll shut up if I'm still outnumbered.

With a tool like this, we're unable to control developer decisions at the time they're making them. So things like adding clear method names are beyond the scope of our control. One of the hardest battles I find myself fighting on teams is to make things clear — will the next developer know what this meant?

To that end, I have concerns about removing the namespace because it's the only part of the process we _can_ influence, and we can use that as a way to build a convention that enforces clarity.

With the proposed removal of a namespace, we're looking at the potential for method names like this:

```js
const data = context.byId(123);
```

Is that wrong? No. But is it hard to debug? Absolutely.

However, by namespacing, we add a relatively painless step that instantly clarifies the code:

```js
const data = context.Book.byId(123);
```

It's a small thing, but at the end of the day, my goal is to write code that I don't have to support — and making it easy for other developers to quickly understand what's happening is a big part of removing myself as a bottleneck.

With the move to allow multiple models per data source + the move to remove a namespace, we're opening up a lot of space for confusing things to happen. Does that make sense?

## On executable schemas

> To answer you question to @corycook - to create a data-source for the Universe GraphQL API I would export the schema given to me using makeRemoteExecutableSchema pointed to https://www.universe.com/graphql . Remote schemas don't have typeDefs and resolvers to export, only the executable schema

I'm going to make the argument that this is outside the scope of what GrAMPS is intended to do. If accessing a remote schema was one of my requirements, I'd end up doing something like this:

1. Compose local data sources with GrAMPS
2. Get the remote schema using the Apollo tools
3. Use schema stitching as designed

GrAMPS _could_ tackle this, but at some point we're starting to compete with what Apollo has already done for us. The idea behind GrAMPS is to combine local data sources, so if we're reaching out to external data sources, that seems to be a different problem to solve — and one that I don't think GrAMPS needs to handle since it's already built into Apollo for us.

Assuming no one has a strong objection to this, are there any other use cases where a data source would need to be executable? Unless there's a use case I'm missing, I'm leaning pretty strongly toward not supporting executable schemas as a design decision.

## On schema stitching

This is probably going to be a longer discussion, so I've created a new issue (https://github.com/gramps-graphql/gramps/issues/2) to continue it.

**Comment by ecwyne** [comment]
Very excited to get https://github.com/gramps-graphql/gramps up and running! Thanks @jlengstorf 

Using third-party schemas like the Universe API is not the only reason for remote schemas. Consider the following example with three (internal) services that use three different database solutions. If I am not able to use remote schemas I must give the GrAMPS gateway **ALL** of the libraries and credentials necessary to access those databases directly from the resolvers. This leads to a fat GrAMPS gateway both in terms of the sheer size of the generated bundle (some libraries will be very large) and in terms of the amount of business logic the GrAMPS gateway is responsible for.

<img width="428" alt="screen shot 2017-11-01 at 8 22 57 am" src="https://user-images.githubusercontent.com/5205440/32282104-eceaf3a4-bedd-11e7-94ce-33f8cccfffb2.png">

Alternatively, if I own a service and expose my own GraphQL interface I am in control of all of my own libraries and credentials. I keep the GrAMPS gateway small and maintain independent deployability.
The following requires the use of remote schemas on the GrAMPS gateway.
<img width="579" alt="screen shot 2017-11-01 at 8 23 54 am" src="https://user-images.githubusercontent.com/5205440/32282144-07649b40-bede-11e7-95d9-eb2706ca0687.png">

I concede that these services **could** expose a RESTful interface for the GrAMPS gateway to consume, but we're trying to make the whole world speak GraphQL, right? Why would I double my work if I'm creating a **new** service.

**Comment by ecwyne** [comment]
My last two cents on namespace

From the perspective of a data-source author
```javascript
export const model = ... // this

export const resolvers = {
  Query: {
    someQuery: (root, args, model) => ... // should be the same as this
  }
}
```

I'm in control of what the model looks like, so I'm not surprised by what shows up in the resolver.

> If another team decides to take down their data source is that going to affect my code because I am depending on that context to be available? If I'm not controlling the GrAMPS instance then I really can't tell what context might contain.

Data source authors shouldn't even have the capability of touching the context of other data sources.

**Comment by jlengstorf** [comment]
I'm open to seeing ideas that would allow GrAMPS to consume executable schemas, but what you're describing sounds like it might be a better fit for what @stubailo was talking about regarding GraphQL Gateways:

![image](https://user-images.githubusercontent.com/163561/32287407-f490111a-beed-11e7-958f-145cb0dc8757.png)

I'm open to PRs for both restricting the context per-data source and making executable schemas work easily, but I want to prioritize making data sources easy to create, work with, and maintain over broadening the scope. I have a lot of non-GraphQL developers to onboard into this system, and the goal of GrAMPS is to provide structure and predictability for tackling common use cases. It's not feasible to expect that every team member will have time to learn the full scope and capabilities of GraphQL, and in most cases they shouldn't have to care — that's what GrAMPS is aiming to solve.

If we broaden our scope too much, then we've lost that and we're basically reimplementing Apollo features. So again, that's not to say that we _can't_ do it, but that I'm going to prioritize the ease of onboarding and writing comprehensive docs over covering all the edge cases. (I feel like my tone may come across as combative here, but it's definitely not intended to be.)

**Comment by jlengstorf** [comment]
@ecwyne @corycook If we can find a way to implement this that's easy for the person who didn't write it, I'm on board for scoping the model to the data source. You both make good points, and this:

```js
export const model = ... // this

export const resolvers = {
  Query: {
    someQuery: (root, args, model) => ... // should be the same as this
  }
}
```

does make sense to me. The docs need to make it really clear to developers that there's a direct correlation of the dataSource.model to the resolver's `context`.

It also needs to be easy and non-hacky to get the `req` into that context, which I know we've talked about but we haven't actually implemented anywhere.

**Comment by jlengstorf** [comment]
Closing now that the 1.x data source format has stabilized.
